name: Destroy IaC
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch para destroy"
        default: "master"
        required: true
        type: string
env:
  REPOSITORY_NAME: iac-devops-ai-project
  REPOSITORY_NAME_LC: iac-devops-ai-project
  APPLICATION: iac-devops-ai-project
  APPLICATION_LC: iac-devops-ai-project
  ORGANIZATION: alexandresouza-gft
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_CLOUD_REGION: us-east-1

jobs:
 Destroy-IA-Devops-Stack:
    runs-on: ubuntu-latest

    environment:
      name: puc-minas

    container:
      image: ubuntu:latest
      options: --user root

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Pre-Config
        run: |
          apt update
          apt install -y \
            openssh-client openssh-server \
            rsync grsync git sshpass curl jq unzip \
            gpg lsb-release ca-certificates

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          ./aws/install

      - name: Install Terraform
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
          apt update && apt install -y terraform

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
          aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
          aws configure set region "$AWS_CLOUD_REGION"
          aws sts get-caller-identity

      # ====== Terraform Destroy ======
      - name: Terraform Destroy
        id: tf
        shell: bash
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_CLOUD_REGION }}
        run: |
          terraform init -input=false
          terraform plan -input=false -no-color
          terraform destroy -input=false -auto-approve
